config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :laps
  resources :races
  resources :pilot_teams
  resources :championships
  resources :pilots
  resources :circuits
  resources :teams
  resources :brands
  
  
  root 'brands#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :circuit
  belongs_to :championship
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  # GET /races or /races.json
  def index
    @races = Race.all
  end

  # GET /races/1 or /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races or /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1 or /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1 or /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def race_params
      params.require(:race).permit(:name, :circuit_id, :championship_id)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_for(race) do |f| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :circuit_id %>
    <%= collection_select(:race, :circuit_id, Circuit.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :championship_id %>
    <%= collection_select(:race, :championship_id, Championship.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Races</h1>

<table class="table table-primary table-striped table-md table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Circuit</th>
      <th>Championship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.name %></td>
        <td><%= race.circuit.name %></td>
        <td><%= race.championship.name %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Circuit:</strong>
  <%= @race.circuit %>
</p>

<p>
  <strong>Championship:</strong>
  <%= @race.championship %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>