config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :laps
  resources :races
  resources :pilot_teams
  resources :championships
  resources :pilots
  resources :circuits
  resources :teams
  resources :brands
  
  
  root 'brands#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lap.rb
class Lap < ApplicationRecord
  belongs_to :pilot
  belongs_to :race
end

app/controllers/laps_controller.rb
class LapsController < ApplicationController
  before_action :set_lap, only: %i[ show edit update destroy ]

  # GET /laps or /laps.json
  def index
    @laps = Lap.all
  end

  # GET /laps/1 or /laps/1.json
  def show
  end

  # GET /laps/new
  def new
    @lap = Lap.new
  end

  # GET /laps/1/edit
  def edit
  end

  # POST /laps or /laps.json
  def create
    @lap = Lap.new(lap_params)

    respond_to do |format|
      if @lap.save
        format.html { redirect_to @lap, notice: "Lap was successfully created." }
        format.json { render :show, status: :created, location: @lap }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laps/1 or /laps/1.json
  def update
    respond_to do |format|
      if @lap.update(lap_params)
        format.html { redirect_to @lap, notice: "Lap was successfully updated." }
        format.json { render :show, status: :ok, location: @lap }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laps/1 or /laps/1.json
  def destroy
    @lap.destroy
    respond_to do |format|
      format.html { redirect_to laps_url, notice: "Lap was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lap
      @lap = Lap.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lap_params
      params.require(:lap).permit(:number, :position, :time, :pilot_id, :race_id)
    end
end

app/helpers/laps_helper.rb
module LapsHelper
end

app/views/laps/_form.html.erb
<%= form_for(lap) do |f| %>
  <% if lap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lap.errors.count, "error") %> prohibited this lap from being saved:</h2>

      <ul>
      <% lap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :time %>
  </div>

  <div class="field">
    <%= f.label :pilot_id %>
    <%= collection_select(:lap, :pilot_id, Pilot.all, :id, :name) %>
  </div>


  <div class="field">
    <%= f.label :race_id %>
    <%= collection_select(:lap, :race_id, Race.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/laps/edit.html.erb
<h1>Editing Lap</h1>

<%= render 'form', lap: @lap %>

<%= link_to 'Show', @lap %> |
<%= link_to 'Back', laps_path %>

app/views/laps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laps</h1>

<table class="table table-primary table-striped table-md table-hover">
  <thead class="table-dark">
    <tr>
      <th>Number</th>
      <th>Position</th>
      <th>Time</th>
      <th>Pilot</th>
      <th>Race</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laps.each do |lap| %>
      <tr>
        <td><%= lap.number %></td>
        <td><%= lap.position %></td>
        <td><%= lap.time %></td>
        <td><%= lap.pilot.name %></td>
        <td><%= lap.race.name %></td>
        <td><%= link_to 'Show', lap %></td>
        <td><%= link_to 'Edit', edit_lap_path(lap) %></td>
        <td><%= link_to 'Destroy', lap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lap', new_lap_path %>

app/views/laps/new.html.erb
<h1>New Lap</h1>

<%= render 'form', lap: @lap %>

<%= link_to 'Back', laps_path %>

app/views/laps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @lap.number %>
</p>

<p>
  <strong>Position:</strong>
  <%= @lap.position %>
</p>

<p>
  <strong>Time:</strong>
  <%= @lap.time %>
</p>

<p>
  <strong>Pilot:</strong>
  <%= @lap.pilot %>
</p>

<p>
  <strong>Race:</strong>
  <%= @lap.race %>
</p>

<%= link_to 'Edit', edit_lap_path(@lap) %> |
<%= link_to 'Back', laps_path %>