config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :laps
  resources :races
  resources :pilot_teams
  resources :championships
  resources :pilots
  resources :circuits
  resources :teams
  resources :brands
  
  
  root 'brands#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pilot.rb
class Pilot < ApplicationRecord
    has_many :pilot_teams
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_action :set_pilot, only: %i[ show edit update destroy ]

  # GET /pilots or /pilots.json
  def index
    @pilots = Pilot.all
  end

  # GET /pilots/1 or /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots or /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: "Pilot was successfully created." }
        format.json { render :show, status: :created, location: @pilot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1 or /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: "Pilot was successfully updated." }
        format.json { render :show, status: :ok, location: @pilot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1 or /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url, notice: "Pilot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pilot_params
      params.require(:pilot).permit(:name, :last_name)
    end
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/pilots/_form.html.erb
<%= form_for(pilot) do |f| %>
  <% if pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
      <% pilot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pilots/edit.html.erb
<h1>Editing Pilot</h1>

<%= render 'form', pilot: @pilot %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilots_path %>

app/views/pilots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pilots</h1>

<table class="table table-primary table-striped table-md table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pilots.each do |pilot| %>
      <tr>
        <td><%= pilot.name %></td>
        <td><%= pilot.last_name %></td>
        <td><%= link_to 'Show', pilot %></td>
        <td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
        <td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pilot', new_pilot_path %>

app/views/pilots/new.html.erb
<h1>New Pilot</h1>

<%= render 'form', pilot: @pilot %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pilot.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pilot.last_name %>
</p>

<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>